spring:
  application:
    name: api-deliveries
  datasource:
    url: jdbc:postgresql://localhost:5432/api-deliveries
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl_auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  springdoc:
    override-with-generic-response: false # Desabilita respostas genéricas na documentação
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui
      enabled: true

logging:
  level:
    org:
      springframework:
        security=DEBUG:

